name: CI
on:
  push:
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: yarn,build
        run: |
          yarn
          yarn build
      - run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.VITE_SHELL_ELECTRON_BUILDER }}
        # uses: primer/publish@3.0.0
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   NPM_AUTH_TOKEN: ${{secrets.VITE_SHELL_ELECTRON_BUILDER}}