name: CI
on:
  push:
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2
        with:
          version: 6.31.0
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{secrets.VITE_SHELL_ELECTRON_BUILDER}}

        with:
          default_branch: 'release'
          dir: '.'
